/* Generated By:JavaCC: Do not edit this line. GrammarTreeConstants.java Version 4.1d1 */
package com.doing.parse.asParse;

public interface GrammarTreeConstants
{
  public int JJTSPECIFICATION = 0;
  public int JJTSPECUNIT = 1;
  public int JJTSIGUNIT = 2;
  public int JJTAXIOMUNIT = 3;
  public int JJTDEFUNIT = 4;
  public int JJTOBSERVABILITY = 5;
  public int JJTEXTENDSSORTS = 6;
  public int JJTEXTENDSSORTLIST = 7;
  public int JJTUSESSORTS = 8;
  public int JJTUSESSORTLIST = 9;
  public int JJTSIGNATURE = 10;
  public int JJTCONSTANT = 11;
  public int JJTCONSTLIST = 12;
  public int JJTATTRIBUTE = 13;
  public int JJTATTRLIST = 14;
  public int JJTATTRIBUTETYPE = 15;
  public int JJTATTROPIDS = 16;
  public int JJTINDEX = 17;
  public int JJTINDEXSET = 18;
  public int JJTSINGLEINDEX = 19;
  public int JJTOPERATION = 20;
  public int JJTOPLIST = 21;
  public int JJTOPER = 22;
  public int JJTDOMAINTYPE = 23;
  public int JJTCODOMAINTYPE = 24;
  public int JJTAXIOMS = 25;
  public int JJTAXIOMLIST = 26;
  public int JJTAXIOM = 27;
  public int JJTVARDECLARATIONS = 28;
  public int JJTVARSORTPAIRS = 29;
  public int JJTVARIDS = 30;
  public int JJTTYPE = 31;
  public int JJTEQUATIONS = 32;
  public int JJTEQUATION = 33;
  public int JJTCONDEQUATION = 34;
  public int JJTLETEQUATION = 35;
  public int JJTCONDEQUATIONS = 36;
  public int JJTCONDITION = 37;
  public int JJTRELATIONOP = 38;
  public int JJTCONDITIONS = 39;
  public int JJTVARDEFINITIONS = 40;
  public int JJTVARASSIGNMENT = 41;
  public int JJTTERM = 42;
  public int JJTADDEXPRESSION = 43;
  public int JJTMULTICATIVEEXPRESSION = 44;
  public int JJTUNARYEXPRESSION = 45;
  public int JJTPARAMETER = 46;
  public int JJTBOOLTERM = 47;
  public int JJTIDENTIFIER = 48;
  public int JJTBASICTYPE = 49;


  public String[] jjtNodeName = {
    "specification",
    "SpecUnit",
    "SigUnit",
    "AxiomUnit",
    "DefUnit",
    "Observability",
    "ExtendsSorts",
    "ExtendsSortList",
    "UsesSorts",
    "UsesSortList",
    "Signature",
    "Constant",
    "ConstList",
    "Attribute",
    "AttrList",
    "AttributeType",
    "AttrOpIDs",
    "Index",
    "IndexSet",
    "SingleIndex",
    "Operation",
    "OpList",
    "Oper",
    "DomainType",
    "CodomainType",
    "Axioms",
    "AxiomList",
    "Axiom",
    "VarDeclarations",
    "VarSortPairs",
    "VarIDs",
    "Type",
    "Equations",
    "Equation",
    "CondEquation",
    "LetEquation",
    "CondEquations",
    "Condition",
    "RelationOP",
    "Conditions",
    "VarDefinitions",
    "VarAssignment",
    "Term",
    "AddExpression",
    "MulticativeExpression",
    "UnaryExpression",
    "Parameter",
    "BoolTerm",
    "Identifier",
    "BasicType",
  };
}
/* JavaCC - OriginalChecksum=6dbf60957df3e5b5796f2268d80ff2a9 (do not edit this line) */
