package com.doing.parse.asParse;

public enum TypeError {
	   PACKAGE_DUPLICATION, PACKAGE_NOT_DEFINED, PACKAGE_IMPORTED_DUPLICATION, 
	   SORT_CONFLICT, SORT_DUPLICATION, SORT_NOT_DEFINED, 
	   WRONG_OBSERVABILITY,  PACKAGE_IMPORTED_SELF, 
	   SORT_PARAMETER_DUPLICATION, SORT_IMPORTED_DUPLICATION, SORT_Super_DUPLICATION,
	   UNIQUE_DUPLICATION, PARAMETER_NOT_MATCH, 
	   OPERATION_CONFLICT,  OPERATION_NOT_DEFINED, TYPESORT_NOT_Dclared,TERMSTYPE_NOT_AGREE,
	   TYPESORT_NOT_DEFINED, DOMAINSORT_NOT_DEFINED, CODOMAINSORT_NOT_DEFINED,
	   VARIABLE_CONFLICT, VARIABLE_NOT_DEFINED, 
	   WRONG_TYPE, TYPE_NOT_EQUAL, WRONG_USAGE,
	   ArrayListOverflow,FileModified
}

